default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  host: localhost
  port: 3306


development:
  <<: *default
  database: defaultdb

test:
  <<: *default
  database: defaultdb_test

production:
  <<: *default
  database: defaultdb_prod
