default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] || 14906 %>
  ssl_mode: REQUIRED
  database: <%= ENV['DATABASE'] %>

development:
  <<: *default
 

test:
  <<: *default
  database: <%= ENV['DATABASE'] %>_test

production:
  <<: *default
  database: <%= ENV['DATABASE'] %>_prod
