default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: avnadmin
  password: AVNS_fYUd4tlARNsh97hD4rT
  host: mysql-salman-logiapp.g.aivencloud.com
  port: 14906
  ssl_mode: REQUIRED
  database: defaultdb

development:
  <<: *default
  database: defaultdb

test:
  <<: *default
  database: defaultdb_test

production:
  <<: *default
  database: defaultdb_prod
